import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'card-form' },
  { path: 'accessible', loadComponent: () => import('./components/accessible/accessible').then((m) => m.AccessibleComponent) },
  { path: 'accessible-checkbox', loadComponent: () => import('./components/accessible-checkbox/accessible-checkbox').then((m) => m.AccessibleCheckboxComponent) },
  { path: 'autocomplete', loadComponent: () => import('./components/autocomplete/autocomplete').then((m) => m.AutocompleteComponent) },
  { path: 'button-icons', loadComponent: () => import('./components/button-icons/button-icons').then((m) => m.ButtonIconsComponent) },
  { path: 'card-form', loadComponent: () => import('./components/card-form/card-form').then((m) => m.CardFormComponent) },
  { path: 'cascadeselect', loadComponent: () => import('./components/cascadeselect/cascadeselect').then((m) => m.CascadeselectComponent) },
  { path: 'clicked', loadComponent: () => import('./components/clicked/clicked').then((m) => m.ClickedComponent) },
  { path: 'color', loadComponent: () => import('./components/color/color').then((m) => m.ColorComponent) },
  { path: 'custom-icon-image', loadComponent: () => import('./components/custom-icon-image/custom-icon-image').then((m) => m.CustomIconImageComponent) },
  { path: 'datepicker', loadComponent: () => import('./components/datepicker/datepicker').then((m) => m.DatepickerComponent) },
  { path: 'file-upload', loadComponent: () => import('./components/file-upload/file-upload').then((m) => m.FileUploadComponent) },
  { path: 'float-label', loadComponent: () => import('./components/float-label/float-label').then((m) => m.FloatLabelComponent) },
  { path: 'html-checkbox', loadComponent: () => import('./components/html-checkbox/html-checkbox').then((m) => m.HtmlCheckbox) },
  { path: 'input-otp', loadComponent: () => import('./components/input-otp/input-otp').then((m) => m.InputOtpComponent) },
  { path: 'input-to-username', loadComponent: () => import('./components/input-to-username/input-to-username').then((m) => m.InputToUsernameComponent) },
  { path: 'knob', loadComponent: () => import('./components/knob/knob').then((m) => m.KnobComponent) },
  { path: 'overlay-animation', loadComponent: () => import('./components/overlay-animation/overlay-animation').then((m) => m.OverlayAnimationComponent) },
  { path: 'programmatic', loadComponent: () => import('./components/programmatic/programmatic').then((m) => m.ProgrammaticComponent) },
  { path: 'radio-button', loadComponent: () => import('./components/radio-button/radio-button').then((m) => m.RadioButtonComponent) },
  { path: 'rating', loadComponent: () => import('./components/rating/rating').then((m) => m.RatingComponent) },
  { path: 'select-button', loadComponent: () => import('./components/select-button/select-button').then((m) => m.SelectButtonComponent) },
  { path: 'semantic-html', loadComponent: () => import('./components/semantic-html/semantic-html').then((m) => m.SemanticHtml) },
  { path: 'size', loadComponent: () => import('./components/size/size').then((m) => m.Size) },
  { path: 'slider', loadComponent: () => import('./components/slider/slider').then((m) => m.SliderComponent) },
  { path: 'speed-dial', loadComponent: () => import('./components/speed-dial/speed-dial').then((m) => m.SpeedDialComponent) },
  { path: 'spin', loadComponent: () => import('./components/spin/spin').then((m) => m.SpinComponent) },
  { path: 'textarea', loadComponent: () => import('./components/textarea/textarea').then((m) => m.TextareaComponent) },
  { path: '**', redirectTo: 'card-form' }
];
